### ISSUE TITLE
Remove resources created during runtime (housekeeping)

### ISSUE THREAD

**Issue by kayman-mk** [cattle-ops/terraform-aws-gitlab-runner#623]
As soon as the module is deployed it creates some resources during runtime. Namely:
- key pairs
- spot instance requests

These resources should be deleted as soon as possible. Afterwards we can get rid of the shell script to terminate the spot requests. I guess nobody is running so that it might happen that spot instances are ordered for outdated spot requests.

Proposal:
In case an Agent is terminated, we should housekeep all unused resources. We already have a Lambda function running for this purpose. It terminates the Executors created by the Agent. We should make this Lambda function mandatory.

- [x] make the lambda function mandatory and remove the variables that should be managed by the module itself (#628)
- [x] delete all unused key pairs (#652)
- [x] terminate all spot instance requests of the terminated Agent (#653)
- [x] amend docs to describe how to remove the module. Should be something like
    - set desired capacity of ASG to 0 so no new instances are created
    - kill all agents, if any. This removes all resources created during runtime (lifecycle hook)
    - Wait for 60s so the lambda function can run
    - run `terraform apply` or `terraform destroy` whatever is applicable
    #654 

Closes #592 (key pairs)
Closes #493 (spot requests)

**Comment by kayman-mk** [comment]
Fully implemented
